
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ 3-configure ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: |
          ./mvnw -B package --file pom.xml
          mkdir artifacts && cp target/*.jar artifacts

      - name: Persist Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JARtifact
          path: artifacts

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Retrieve Artifact
        uses: actions/download-artifact@v2
        with:
          name: JARtifact

      - name: Install Heroku
        run: |
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku plugins:install java

      - name: Heroku deploy jar
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku deploy:jar devops-0.0.1-SNAPSHOT.jar --jdk 11 -a <INSERT_STG_APP_HERE>
